name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: nice_nano_v2
            shield: corne_left nice_view_adapter nice_view
          - board: nice_nano_v2
            shield: corne_right nice_view_adapter nice_view
          - board: nice_nano_v2
            shield: settings_reset

    steps:
      - name: Checkout ZMK Config
        uses: actions/checkout@v4

      - name: Clone Urob's ZMK fork (without workflows)
        run: |
          rm -rf zmk
          git clone --depth 1 --branch main https://github.com/urob/zmk.git zmk
          rm -rf zmk/.github
          ls -la zmk

      - name: Set up Zephyr and west
        run: |
          pip install west
          west init -l zmk/app
          west update

      - name: Build Firmware
        run: |
          west build -s zmk/app -d build/${{ matrix.shield }} \
            -b ${{ matrix.board }} \
            -- -DZMK_CONFIG=${{ github.workspace }}/config \
               -DSHIELD="${{ matrix.shield }}" \
               -DZMK_EXTRA_MODULES=${{ github.workspace }}

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.shield }}
          path: build/${{ matrix.shield }}/zephyr/*.uf2
