name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: nice_nano_v2
            shield: corne_left nice_view_adapter nice_view
          - board: nice_nano_v2
            shield: corne_right nice_view_adapter nice_view
          - board: nice_nano_v2
            shield: settings_reset

    steps:
      # 1️⃣ Hent din ZMK config (dit eget repo)
      - name: Checkout ZMK Config
        uses: actions/checkout@v4

      # 2️⃣ Download urob/zmk som ZIP (uden GitHub workflows)
      - name: Download urob/zmk (latest main)
        run: |
          mkdir -p external
          curl -L https://github.com/urob/zmk/archive/refs/heads/main.zip -o zmk.zip
          unzip -q zmk.zip -d external
          mv external/zmk-main external/zmk
          rm -rf external/zmk/.github

      # 3️⃣ Installer West (Zephyr værktøj)
      - name: Install West
        run: pip install west

      # 4️⃣ Init og opdater West workspace
      - name: Initialize Zephyr (West)
        run: |
          west init -l external/zmk/app
          west update

      # 5️⃣ Build firmware for hver matrix (left/right/reset)
      - name: Build firmware
        run: |
          west build -s external/zmk/app -d build/${{ matrix.shield }} \
            -b ${{ matrix.board }} \
            -- -DZMK_CONFIG=${{ github.workspace }}/config \
               -DSHIELD="${{ matrix.shield }}" \
               -DZMK_EXTRA_MODULES=${{ github.workspace }}

      # 6️⃣ Upload .uf2 som artifact (til download)
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.shield }}
          path: build/${{ matrix.shield }}/zephyr/*.uf2
